/**
 * 请求状态吗
 */
 const STATUS_CODE = {
    SUCCESS: 1,
    ERROR: 0,
    FIELD_LENGTH_ERROR: 2,
    PARAMS_TYPE_ERROR: 3,
    USER_ALREADY_EXIST: 4,
    PASSWORD_ERROR: 5,
    PARAMS_ERROR: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403
  };